const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || "",
    ownerName: process.env.OWNER_NAME || "Blessed",
    ownerNumber: process.env.OWNER_NUMBER || "2348165846414",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ0RCYW5MLzhYa3lsM1RlZXB4NFRNZWFvZERrSzN3YXdRbGQ4eFYvQ2UxND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTEpKS2VGZnV6N1VTbjR5bTRWVmtmMloxb3ZUWU9ySWR0VGVKQU9qVDIyRT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLSklxNU9NbHM4dDFwNkFrc2xER3FlcU14M2NOYXRMOTVna3pMZDBhNlVBPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJGMThlSXFXVFdXMGthdThVOVhjTnRQSVkzWEovOWpQaHhPeFpoSExIS3o4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjBHZU9FUnduTG5rZ3lZdXlTWjJQWW1QbXJVYVJIWEdyUUdpQ0xFb1hpbkU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtUZGxncHo2OFl5aDBlREhRN3lFclcxYlhoVHYvWXhUd0VKRGxqNkdoRDQ9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaVAvd21PQ0EyR2VBV204Q0xnVnRhUExBbnhUYU15ckpGT1h4SmN2c2FGND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQjNDR3ZXRHNOakV5czBNWm0rcFpDU3J5VXFuREZBL2RQaWRrOFo3OFVIYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjlZaEt4YTVHZE9KOW1lVmJ5dXlmYUxoN0xOdlY5SjBCWGE3VElMSTNDblJBMlFvZWdvRnNrQ2taK3VxMDdoM3h3dXAzdWpzZzF3WkJteDNZWmtHS2pRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjIyLCJhZHZTZWNyZXRLZXkiOiJ0ZmVUWDVXdW5UbkJzTTlyZmJGa1ZvTmtZT3JCcDNVOHczN1g0WDErY2gwPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJUVk02WkdSSyIsIm1lIjp7ImlkIjoiMjc3NjIxMzUzNDQ6MTFAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIxMjk2NTI4NDg4Njk0MDA6MTFAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNMbWIrWndIRUtHNnJiMEdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJESXlOVGx0NCtKQnVRVXpubmlicjFRRzBCbEIvSkNZa3RrK3dLM3loeDBVPSIsImFjY291bnRTaWduYXR1cmUiOiIxY3ljUUJoRjlVNUtvV3Uyd3pRbUZHSUh4WTNlMTdqL0hXbXJ1WUJXTS9BZ2pMYmR3ZFpUajdDVWFoUXZoM1ZZd0ZyU2ZhVXJsb0ZBazBtZWcwUGdCdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiTkpUOGJjREFlZVBKSHY0YVU4RktmM3hoNUUyaG1kMFB5VEFHeXA3dHlXdjJtSkNkeUJnK1VUZVYwaW1INHZLTFlVcEpZdjdsV1lPVUZVMWJ2VnExZ1E9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNzc2MjEzNTM0NDoxMUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJReU1qVTViZVBpUWJrRk01NTRtNjlVQnRBWlFmeVFtSkxaUHNDdDhvY2RGIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQWdJQWc9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzkyODM3NTgsImxhc3RQcm9wSGFzaCI6IjJWNzdxVSIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBTnhNIn0=",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
